name: Deploy DotNet project to Azure function app with a Windows environment

on:
  repository_dispatch:
    types: build-azure-function        

env:
  AZURE_FUNCTIONAPP_NAME: samplefunctions00  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './DemoFunction'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.402'              # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.branch || 'master' }}
        path: AzureFunction
    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ github.event.client_payload.name }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: '<publishData><publishProfile profileName="samplefunctions00 - Web Deploy" publishMethod="MSDeploy" publishUrl="samplefunctions00.scm.azurewebsites.net:443" msdeploySite="samplefunctions00" userName="${{github.event.client_payload.username}}" userPWD="ogAzDjLj68e0cLE0GYogHc1sjai4SDfc4uBxLlX5TNmbaZiTLfDGGdJCMtFi" destinationAppUrl="http://samplefunctions00.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>'
